logging:
  level.: ERROR
  level.org.springframework: ERROR
  level.org.springframework.web: ERROR
server:
  servlet:
    context-path: "/begrep/"
management:
  server:
    port: 8181
  endpoints:
    web:
      base-path: "/begrep/"
      exposure:
        include: "prometheus,metrics,info,health"
